app:
  name: sasya

jwt:
  header: Authorization
  expires_in: 300 # 5 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: sasya

spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create-drop
datasource:
    url: jdbc:mysql://localhost/testdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

